### ISSUE TITLE
Tenacity Does Not Open on PopOS 22.04

### ISSUE THREAD

**Issue by therealayayron** [tenacityteam/tenacity-flatpak-nightly#5] opened 2022-06-30 03:01 UTC
Tenacity does not seem to be opening.

I do see a microphone in the upper right-hand corner of the menu (as if it's open and a microphone is attached).

But nothing opens. When I try to open Tenacity again by clicking on the icon (again), I get the following error:

"An unrecoverable error has occurred during startup"

I am unable to open the application via the terminal using the following command:

`flatpak run org.tenacityaudio.Tenacity`

I do not get any errors in the terminal from running the aforementioned command.

**Comment by TheEvilSkeleton** [comment] 2023-01-15 21:35
Closing since we don't know if it's still reproducible.

**Closed as completed by TheEvilSkeleton** 2023-01-15 21:35 UTC
